# Start from golang base image
FROM postgres:latest

           # Add Maintainer info
LABEL maintainer="Database"

           # Setup folders
RUN mkdir /app
WORKDIR /app
RUN mkdir migrations

COPY ../api/db/migrations/* /migrations
RUN migrate -path ../api/db/migrations -database "postgresql://root:i76248591M@localhost:5432/ships_data?sslmode=disable"-verbose up

EXPOSE 5432