# Start from golang base image
FROM postgres:latest

# Add Maintainer info
LABEL maintainer="Database"

# Setup folders
RUN mkdir /app
WORKDIR /app
RUN mkdir migrations

COPY ../api/db/migrations/*.sql /migrations
RUN docker exec -it scalefocusdb createdb --username=${DB_USER} --owner=${DB_PASSWORD}
RUN migrate -path ../api/db/migrations -database "postgresql://${DB_USER}:${DB_PASSWORD}@localhost:5432/ships_data?sslmode=disable"-verbose up

EXPOSE 5432