version: '3.9'
services:
  app:
    container_name: cadetproject
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - ${API_PORT}:${API_PORT}
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - postgresdb
    networks:
      - learning

  postgresdb:
    image: postgres:latest
    container_name: scalefocusdb
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - database_postgres:/var/lib/postgresql/data
      - ./db/migration/000001_init_schema.up.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - learning
volumes:
  api:
  database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  learning:
    driver: bridge